[package]
name = "buffers"
version = "0.0.1"
edition = "2021"

[dependencies]
regex = "1.3.1"
lazy_static = "1.4.0"
tensorflow = { version = "0.18.0", features = ["tensorflow_unstable"] }

[profile.release]
strip = "symbols"
