version: '3'

dotenv: ['.env']

tasks:
  build_receiver:
    desc: Build IRC receiver
    cmds:
      - rm receiver
      - gcc -Wall -Wconversion receiver.c -o receiver
      - strip receiver

  build_sender:
    desc: Build IRC sender
    cmds:
      - rm sender
      - gcc -Wall -Wconversion sender.c -o sender
      - strip sender

  run_receiver:
    desc: Run IRC receiver
    cmds:
      - task: build_receiver
      - ./receiver $(cat ./oauth.txt) rprtr258

  run_sender:
    desc: Run IRC sender
    cmds:
      - task: build_sender
      - ./sender $(cat ./oauth.txt) rprtr258

  run:
    desc: Launch bot
    cmds:
      - winpty python3 src/main.py

  send:
    desc: Send message from bot
    cmds:
      - python3 src/cmd.py '{{.CLI_ARGS}}'

  init:
    desc: Checkout submodules, init database and build balaboba binary
    cmds:
      - git submodule update --init --recursive
      - sqlite3 db.db < sql/init.sql
      - (cd src/balaboba; go build -o ../../balaboba cmd/cmd.go)

  linter:
    desc: Run linter
    dir: src
    cmds:
      - flake8 --filename *.py --max-line-length 120 --ignore=E302,E305 --exclude __init__.py

  get_chat_logs:
    desc: Collect data for training markov chain
    generates: [dataset]
    cmds:
      - tcd -q --channel screamlark --first 10
      - cat *.txt | rg -v 'StreamElements' | cut -d' ' -f3- > logs
      - cat dataset logs | rg -v '(!(g|say)|Продолжай кормить рыбку!|ставки|^\d{1,3} \d{1,3}$)' | sort -u > tmp_dataset
      - mv tmp_dataset dataset
      - rm logs

  train:
    desc: Train markov chain on collected data
    deps: [get_chat_logs]
    sources: [dataset]
    generates: [model.json]
    cmds:
      - python quotes_generator/main.py train --dataset dataset --model model.json

  commit:
    desc: Commit to git
    cmds:
      - venv/Scripts/pip freeze > requirements.txt
      - task: linter
      - cmd: git add .
        ignore_error: true
      - git status
      - cmd: git commit -m "Autocommit"
        ignore_error: true

  push:
    desc: Commit and push to git and heroku
    cmds:
      - git push heroku master
      - git push github master

  deploy-fix:
    desc: Commit, push and deploy
    cmds:
      - task: commit
      - task: push

  deploy:
    desc: Prepare new data, commit, push and deploy
    cmds:
      - task: train
      - task: deploy-fix
  
  dump-db:
    desc: Dump balaboba table into blab.sql and feed table into feed.sql
    cmds:
      - sqlite3 db.db < sql/dump.sql

